### ISSUE TITLE
How do we make offer post?

### ISSUE THREAD

**Issue by allgrowsm** [spotonlive/php-google-my-business#21]
I have following source code.

```
    $obj = new \Google_Service_MyBusiness($this->getClient('mybusiness'));
    $post = new \Google_Service_MyBusiness_LocalPost();
    $offer = new \Google_Service_MyBusiness_LocalPostOffer();
    $offer->setCouponCode($couponCode);
    $offer->setTermsConditions($termsCondition);
    $offer->setRedeemOnlineUrl($redeemOnlineUrl);
    $post->setSummary($summary);                                                                                                                                            
    $post->setOffer($offer);
    $obj->accounts_locations_localPosts->create($accountLocation,$post)
```
It returns following.

```
Google_Service_MyBusiness_LocalPost Object
(
    [collection_key:protected] => media
    [internal_gapi_mappings:protected] => Array
        (
        )

    [alertType] => 
    [callToActionType:protected] => Google_Service_MyBusiness_CallToAction
    [callToActionDataType:protected] => 
    [createTime] => 2020-10-05T10:16:42.650Z
    [eventType:protected] => Google_Service_MyBusiness_LocalPostEvent
    [eventDataType:protected] => 
    [languageCode] => ja
    [mediaType:protected] => Google_Service_MyBusiness_MediaItem
    [mediaDataType:protected] => array
    [name] => accounts/4545/locations/4545/localPosts/45454
    [offerType:protected] => Google_Service_MyBusiness_LocalPostOffer
    [offerDataType:protected] => 
    [searchUrl] => https://local.google.com/place?id=12082631760375401764&use=posts&lpsid=5751090922450244975
    [state] => LIVE
    [summary] => 特典詳細！！！特典詳細！！！特典詳細！！！特典詳細！！！
    [topicType] => STANDARD
    [updateTime] => 2020-10-05T10:16:42.650Z
    [modelData:protected] => Array
        (
        )

    [processed:protected] => Array
        (
        )

)
```

It seems it dose not create offer localPost.
It creates event localPost.

Do you have any suggestion for this?

**Comment by prabodhanpradhan** [comment]
This code created offer post for me.	

			$service = new Google_Service_Mybusiness($client);
				$post_body = new \Google_Service_MyBusiness_LocalPost;
				$post_body->setLanguageCode('en');
				$post_body->setSummary('test offer_1');

				$offer = new \Google_Service_MyBusiness_LocalPostOffer;
				$offer->setCouponCode('TEST-OFFE-CODE');
				$offer->setRedeemOnlineUrl('https://www.example.com');
				$offer->setTermsConditions('Offer not valid, it only test offer');
				$post_body->setOffer($offer);
				
				
				$event = new \Google_Service_MyBusiness_LocalPostEvent;
				$event->setTitle('Test Offer post');
				$schedule= new \Google_Service_MyBusiness_TimeInterval;
				
				$startdate = new \Google_Service_MyBusiness_TimeInterval;
				$date= new \Google_Service_MyBusiness_Date;
				$date->setYear('2021');
				$date->setMonth('10');
				$date->setDay('02');
				$schedule->setStartDate($date);
				
				$starttime = new \Google_Service_MyBusiness_TimeRange;
				$time = new \Google_Service_MyBusiness_TimeOfDay;
				$time->setHours('9');
				$time->setMinutes('0');
				$time->setSeconds('0');
				$time->setNanos('0');
				$schedule->setStartTime($time);
				
				
				$endDate = new \Google_Service_MyBusiness_TimeInterval;
				$date= new \Google_Service_MyBusiness_Date;
				$date->setYear('2021');
				$date->setMonth('10');
				$date->setDay('03');
				$schedule->setEndDate($date);
				
				$endtime = new \Google_Service_MyBusiness_TimeRange;
				$time = new \Google_Service_MyBusiness_TimeOfDay;
				$time->setHours('11');
				$time->setMinutes('0');
				$time->setSeconds('0');
				$time->setNanos('0');
				$schedule->setEndTime($time);
				
				$event->setSchedule($schedule);
				$post_body->setEvent($event);
				$post_body->setTopicType('OFFER');
				
				$media = new \Google_Service_MyBusiness_MediaItem;
				$media->setMediaFormat('PHOTO');
				$media->setSourceUrl('https://image.shutterstock.com/image-photo/white-transparent-leaf-on-mirror-260nw-1029171697.jpg');
				$post_body->setMedia($media);
				print_r($post_body);exit;
				$accounts = $service->accounts->listAccounts()->getAccounts();
				$locations = $service->accounts_locations->listAccountsLocations($accounts[0]['name']);
				$post = $service->accounts_locations_localPosts->create($locations[0]['name'], $post_body);

**Comment by allgrowsm** [comment]
@prabodhanpradhan 
Thank you very much :)
