### ISSUE TITLE
orderBy parameter for listAccountsLocations

### ISSUE THREAD

**Issue by alexp777** [spotonlive/php-google-my-business#5]
MyBusiness.php:346
method: v4/{+parent}/locations
There is absent 'orderBy' in the parameters array.

This is for the following function:
MyBusiness.php:1266
public function listAccountsLocations()

But in the Google refrence it is present.
https://developers.google.com/my-business/reference/rest/v4/accounts.locations/list

Could you add 'orderBy' parameter?

**Comment by nikolajlovenhardt** [comment]
Hi @alexp777 

You're welcome to open a PR and I'll look into it

**Comment by nikolajlovenhardt** [comment]
Hi @alexp777 

You need to pass the orderBy parameter as a optional parameter.

**Comment by alexp777** [comment]
Then there will be an exception

http://nimb.ws/Rjtb6s


2018-09-19 15:06 GMT+03:00, Nikolaj Løvenhardt Petersen
<notifications@github.com>:

**Comment by nikolajlovenhardt** [comment]
Good point - I'll look into it. Thank you

**Comment by JessJNielsen** [comment]
Hi @alexp777 

I have just upgraded the package to version 4.2. 
It contains the orderBy parameter.

**Comment by alexp777** [comment]
Thank you!
